[[Blosc]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "095945534f2b32a9bc2b577159310c8956c739fa"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "ec29bec2784e24e7f7339300141976e2fc57ebc7677ef1a55f908f8fc3457dda"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.14.3+0/Blosc.v1.14.3.aarch64-linux-musl-cxx03.tar.gz"
[[Blosc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c60dd317e55600df16e80046a7104b9ee83b5d9"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "1dcb8d403a508d92618d3c126bc85dea5a35efbdc2eb9f792b22c11ae20afad2"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.14.3+0/Blosc.v1.14.3.aarch64-linux-musl-cxx11.tar.gz"
[[Blosc]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "884e7a369810238144885732b42bcc9556250e11"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "a20404ec181ba276636ce2c67c22f1e99aa0977421f5d91084bb5b242ceda29e"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.14.3+0/Blosc.v1.14.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Blosc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "579a09774380e99d70add2ba8682e426c8d2d76e"
os = "windows"

    [[Blosc.download]]
    sha256 = "372a37fbf39d84c2f2fa40fcc347b75a7bd76823852be802055c96059fb88f3d"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.14.3+0/Blosc.v1.14.3.x86_64-w64-mingw32-cxx11.tar.gz"
[[Blosc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "90226ae7cd93b33686832502a5c197346035d19d"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "4fe0550a8425c3cb97c7ba1f19e226631e8df8d438987725f1046d73a76e8463"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.14.3+0/Blosc.v1.14.3.i686-linux-musl-cxx11.tar.gz"
[[Blosc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6dc8fc6d193b67ec773f39a005ca45c605fac9a7"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "1f799969bef9f10e5d903d5565b1fc0da44fccc516d633e6e7e7b45ad361e0b9"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.14.3+0/Blosc.v1.14.3.x86_64-linux-musl-cxx11.tar.gz"
[[Blosc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0750ed71e59871408ac5ece9d54169ace2e7fc21"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "89683b1eca1bddeb2616e7e307a924e9fbe1c2bbc7e45ec94a609b0e6cf1fe27"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.14.3+0/Blosc.v1.14.3.x86_64-linux-gnu-cxx03.tar.gz"
[[Blosc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0e1a420112628524b3ec5fc404a9d8f3661dcb4e"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "9fbf9bb0b399576a65392b20d14d86c14f64c9276b926ff1d6743c265fc5362b"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.14.3+0/Blosc.v1.14.3.i686-linux-gnu-cxx03.tar.gz"
[[Blosc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "679ed7f2fad0f923533078e691bdd24f23e7e6c2"
os = "macos"

    [[Blosc.download]]
    sha256 = "bb0850013fa4c0fe7e03d41a29a7c88b9ae1640630f51bab34bb224d415beeb3"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.14.3+0/Blosc.v1.14.3.x86_64-apple-darwin14-cxx11.tar.gz"
[[Blosc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ff69bbfc88779768b7821f42a1bd814634b8900"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "31459cf1ca9ceead5820cf85718523a6ae3b7683d80a4c60b87d3f950555b007"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.14.3+0/Blosc.v1.14.3.i686-linux-gnu-cxx11.tar.gz"
[[Blosc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c9bf969647e919359dcbe3f0065ff6ea39317126"
os = "windows"

    [[Blosc.download]]
    sha256 = "c2e90995e0aabb5f9f72964f4c1a1f1dad3b6b65030256922bc2ada00a03dba2"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.14.3+0/Blosc.v1.14.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[Blosc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "992a8dd3f39cb5219d57e90dccdc773ebb37c807"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "0e09d0da7986982af9b0e1d2316e2ad2d835c4d4a19946aa10b940529f63b3ee"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.14.3+0/Blosc.v1.14.3.x86_64-linux-gnu-cxx11.tar.gz"
[[Blosc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "806bce6ce447f4414290ec860d079cd1d0b1901d"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "62d0e5f8b20865de3650c0420e1c1c03ed2b857fa413d9408d8b7b20aa7b34dd"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.14.3+0/Blosc.v1.14.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Blosc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e28c5667c09fad7a68f3e1a53739a195c921df3"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "5a5fc95dc1e79b6446d9dae100b43a75485e4d650ae9e672c2b0519e8b1039e1"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.14.3+0/Blosc.v1.14.3.aarch64-linux-gnu-cxx11.tar.gz"
[[Blosc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "77e0048a9cc591d29b80773cf1e1c1f5b36b1166"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "ef776af5aa9f0c6d1e81743bf0ce8bfb7ee6e93e32ebcd7490357f7c86dc0454"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.14.3+0/Blosc.v1.14.3.x86_64-linux-musl-cxx03.tar.gz"
[[Blosc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "337e0fd9116d9cb068543c493dc464e8b95543ea"
os = "macos"

    [[Blosc.download]]
    sha256 = "6ca293ccdf8226fdc1ae3d66dba7cdb130f9a4a3b66706f67f292d737ca46120"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.14.3+0/Blosc.v1.14.3.x86_64-apple-darwin14-cxx03.tar.gz"
[[Blosc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "995db61e2860f0e3c590d6001b58db84076a3dc4"
os = "freebsd"

    [[Blosc.download]]
    sha256 = "f0dd5e49284d02425a096c285c118ee695388578410d177d410e1d644b22d1cf"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.14.3+0/Blosc.v1.14.3.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[Blosc]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4ca3738dede286a7f20f16954228e1b38ff5691d"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "f60b9736850b06b8c0476b30335807f28d9174146f28b36709e5b9f205736a26"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.14.3+0/Blosc.v1.14.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Blosc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5ce63bb47982a6900dbffaf15404aa351ff75906"
os = "windows"

    [[Blosc.download]]
    sha256 = "9705ccf47ddf2a75ffb20f56bec5756f8d2570824cfa1b0d5c72027c3959b2c6"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.14.3+0/Blosc.v1.14.3.i686-w64-mingw32-cxx03.tar.gz"
[[Blosc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba1ac5ccef409a874a9de2228750d76d028b8f42"
os = "windows"

    [[Blosc.download]]
    sha256 = "5dcd948f7977caac72dacd2a926e7eabeaee8dfaef77c88dee8c12f7433e1ed8"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.14.3+0/Blosc.v1.14.3.i686-w64-mingw32-cxx11.tar.gz"
[[Blosc]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0be0b50bfb23eed81499a6bf80b0474d43578a71"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "165d9aee09392b80bd48618c6f326f727fe4863befa333b50184025aaeea9268"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.14.3+0/Blosc.v1.14.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Blosc]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4b53dc076e13a51e673861b2e71e11bfcf7a4e75"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "5e6c9dc133c7d5cb5557947f0c8a2166ff0c6b98552f7e5ce289c8119cf8e422"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.14.3+0/Blosc.v1.14.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Blosc]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cf2c5762b8d57bd6fdc47dfe4bc7b80962fbe259"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "88f31714b39e23d326c39de5c5f55f7a4a9a419a6b50b0f76232eb2ab402b485"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.14.3+0/Blosc.v1.14.3.aarch64-linux-gnu-cxx03.tar.gz"
[[Blosc]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b974ec6320d8fd13177be688e3c14dd16f0a2080"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "4cbd5bd5898cc8e086949c782a29cb78867fb7176106ae95d7869e5bacd267da"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.14.3+0/Blosc.v1.14.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Blosc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "04368852146c23625e8fab347fe9f4564640ee43"
os = "freebsd"

    [[Blosc.download]]
    sha256 = "c1082af775c969dc81851dfbf7e03b2d02820a2c17442bd418d4cf0495e12ea0"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.14.3+0/Blosc.v1.14.3.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[Blosc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "618cffc4d3c93e83561abf7e5d7c2523d6320ea7"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "c0c3bdd555db3b27202f1b951d3ed2242b42a4c8bc95b2a2c65564ced114342b"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.14.3+0/Blosc.v1.14.3.i686-linux-musl-cxx03.tar.gz"
