[[Blosc]]
arch = "aarch64"
git-tree-sha1 = "c135f81d1627efb61741942e7c241ae1668d962b"
os = "macos"

    [[Blosc.download]]
    sha256 = "7c9af0f9c7af50267b418755b05166eef25c5fa1214a9560c4b2fb59494f0a18"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+1/Blosc.v1.21.6.aarch64-apple-darwin.tar.gz"
[[Blosc]]
arch = "aarch64"
git-tree-sha1 = "55f76839fe48987d1170e196e6c891bc20f7b813"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "8bf42d62c26bccab03aaedfec2df80af255ccc510d0d5aebd27197e1b30ddaae"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+1/Blosc.v1.21.6.aarch64-linux-gnu.tar.gz"
[[Blosc]]
arch = "aarch64"
git-tree-sha1 = "317ac6a999f85fe5b0211edb861aee29cf7de2b7"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "9e51c3006d857bb2d872bf63e5c631263055a2ca02671f4a14c616a466a97db8"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+1/Blosc.v1.21.6.aarch64-linux-musl.tar.gz"
[[Blosc]]
arch = "aarch64"
git-tree-sha1 = "0447900a256098ea612d3e85cf6a46f4f2b7dc40"
os = "freebsd"

    [[Blosc.download]]
    sha256 = "0a3648d495557e9478c27cd65e9231ae3d361a53be2b3305bb58bec81d4ca6a2"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+1/Blosc.v1.21.6.aarch64-unknown-freebsd.tar.gz"
[[Blosc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "298e6af3c0edf99663d23bd044ad91a1adc35ae5"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "c5eb733be0f9b21964c71b1320b4b0d60214e2ddca067351f731ba68618a07fb"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+1/Blosc.v1.21.6.armv6l-linux-gnueabihf.tar.gz"
[[Blosc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3caa5f3b44a745b8571d427fd3708e51b834297b"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "e8b37db5f08c06af037ef3b020449366fe5bb31d74af66c2b0565dcdb916d082"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+1/Blosc.v1.21.6.armv6l-linux-musleabihf.tar.gz"
[[Blosc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "314dad4faa3abbaae9f34c98e1f1f4baee084170"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "5fccfe21109cce8c54995701c169d7dec988769ff58502567795c35741e318c1"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+1/Blosc.v1.21.6.armv7l-linux-gnueabihf.tar.gz"
[[Blosc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f17e9869a36df93f7cf965697903c4140e502891"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "8cf13b40bbdf997e67b07a00fa1c4102d2e92a7d7170bc906e0c81262122f671"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+1/Blosc.v1.21.6.armv7l-linux-musleabihf.tar.gz"
[[Blosc]]
arch = "i686"
git-tree-sha1 = "bccf63754a6892e9dfea881d01c7272c991861f9"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "3c82b6308b56a980b9d36d0a26daca93fb955658ab8457167ce9c38c9ad4b2f7"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+1/Blosc.v1.21.6.i686-linux-gnu.tar.gz"
[[Blosc]]
arch = "i686"
git-tree-sha1 = "8d950b8e76c48abe999088c073c00a01e65e10f3"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "1b05c21b170e102b98972064748d15038d560388cdb2f25c572fb1105245d762"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+1/Blosc.v1.21.6.i686-linux-musl.tar.gz"
[[Blosc]]
arch = "i686"
git-tree-sha1 = "5c234b2a1c46c80d029aa7c3bb8e9a12cae6b4d5"
os = "windows"

    [[Blosc.download]]
    sha256 = "366b17e78294de6217f1aafea4b95c439d40d786960d2477542a68465f34188e"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+1/Blosc.v1.21.6.i686-w64-mingw32.tar.gz"
[[Blosc]]
arch = "powerpc64le"
git-tree-sha1 = "14b7466fef2a8a1970d5294ae0c00bab19f83382"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "65b8ae3bcd1a1140caf5721416fddb429899e0a3013c9793e7748dda2dbce130"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+1/Blosc.v1.21.6.powerpc64le-linux-gnu.tar.gz"
[[Blosc]]
arch = "riscv64"
git-tree-sha1 = "77aff71195295f876db752f2eb44b8e40a4c76ae"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "ebb6ed63cb2d623b55872192726237b08333b4efc2bc739121babf7db28c1140"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+1/Blosc.v1.21.6.riscv64-linux-gnu.tar.gz"
[[Blosc]]
arch = "x86_64"
git-tree-sha1 = "50d31ce78c89142de7281897d56e0c8d6b9f8890"
os = "macos"

    [[Blosc.download]]
    sha256 = "b5fdeb678294829808537db1f7d667c7c199b602780df1e8bc8afb7960298354"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+1/Blosc.v1.21.6.x86_64-apple-darwin.tar.gz"
[[Blosc]]
arch = "x86_64"
git-tree-sha1 = "003de3d5ed9f4b021a02b2b263ce82d2d1bc5773"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "b195cdc1303c3ffc76c48de3d89fd2197c4244b1c8ed910a04a8b4ba3d2e51c9"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+1/Blosc.v1.21.6.x86_64-linux-gnu.tar.gz"
[[Blosc]]
arch = "x86_64"
git-tree-sha1 = "e3011b3a469b12d9d4b69ba4122cd18905bcbade"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "26d53685762ac4a33834408bfaaad46260758ae11cf3bd54d7df0d1a3bce1a0d"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+1/Blosc.v1.21.6.x86_64-linux-musl.tar.gz"
[[Blosc]]
arch = "x86_64"
git-tree-sha1 = "fd4f61fc06ff39f839e0ad434bc9bef8ad7beb13"
os = "freebsd"

    [[Blosc.download]]
    sha256 = "71e94f329da990a41d685457baecbbb4af308246d5fa59b4d40ab467629c650d"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+1/Blosc.v1.21.6.x86_64-unknown-freebsd.tar.gz"
[[Blosc]]
arch = "x86_64"
git-tree-sha1 = "10dbc03f7a896b99bfacacf4c0d67fdb8d9d737e"
os = "windows"

    [[Blosc.download]]
    sha256 = "78e2a233ba46c8bf018c6910fce15ce26d33d4242c343e377f33459f44277385"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+1/Blosc.v1.21.6.x86_64-w64-mingw32.tar.gz"
