[[Blosc]]
arch = "aarch64"
git-tree-sha1 = "187469cfa3f583dba86f229d6f71d00649671ecf"
os = "macos"

    [[Blosc.download]]
    sha256 = "af5d2ed3172be1212d80cf7b1138640d0c1fa5c199d9dbf29daf13528dd59c5a"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.4+0/Blosc.v1.21.4.aarch64-apple-darwin.tar.gz"
[[Blosc]]
arch = "aarch64"
git-tree-sha1 = "a7725bc9df430d733bc97380b209cf4a3232b4eb"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "a203b55cb3f4969d54cb5cab0829001c53da2ca4d0b029f5e945ef85b1630afb"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.4+0/Blosc.v1.21.4.aarch64-linux-gnu.tar.gz"
[[Blosc]]
arch = "aarch64"
git-tree-sha1 = "8eb32cda845dce3a7e5fbc207574b69866cb9359"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "e0b5d67364582ebdc663775c2f1b0c258ee6c76c49583eb688a17c107b865269"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.4+0/Blosc.v1.21.4.aarch64-linux-musl.tar.gz"
[[Blosc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9065699b08dafeb311bdd7e06bf4fa4f1597f68b"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "8d333b924aa7ce697cfbe2c01c1317003939f8ffab0ac3a0a3c9196d29de6cea"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.4+0/Blosc.v1.21.4.armv6l-linux-gnueabihf.tar.gz"
[[Blosc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3a8c14603c649c8f3215debbbac1d024f7a2df08"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "85f88a383459f23ed5f85a2470712fcda9f261c96aa9351b49ff1f0247d44814"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.4+0/Blosc.v1.21.4.armv6l-linux-musleabihf.tar.gz"
[[Blosc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b9964aff998c26b2c0e1d911aa7adc5375da0883"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "1fec79132acebc91b2197fd44b5af24211750cea385f3dccde882764ba5b7dc5"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.4+0/Blosc.v1.21.4.armv7l-linux-gnueabihf.tar.gz"
[[Blosc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a5c999ff6fca31eccb7c3c6838996c0c3d0e18ba"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "a1ac005a248d0cd90e5aab85b8873761b4e2aee4edf8a2f31fcd1fe6c8e60f9e"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.4+0/Blosc.v1.21.4.armv7l-linux-musleabihf.tar.gz"
[[Blosc]]
arch = "i686"
git-tree-sha1 = "05aa02ff981a115062d623ae33a60e53924e9b0c"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "e99cd0d8f0c9db3a537af2e26c4a4b8ffa3406b2ba6c16b312b66278a1bce34f"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.4+0/Blosc.v1.21.4.i686-linux-gnu.tar.gz"
[[Blosc]]
arch = "i686"
git-tree-sha1 = "c4f2f68aafa99ef0f16d6bc7905cc3b2f1011b65"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "9c9ab82911e8b586a31cc6f99787e838c38b567d80cad2afb89805519c536e7a"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.4+0/Blosc.v1.21.4.i686-linux-musl.tar.gz"
[[Blosc]]
arch = "i686"
git-tree-sha1 = "2e864d833bbdfbc840adaf03f1aa39f0f7b6694d"
os = "windows"

    [[Blosc.download]]
    sha256 = "4944843d8d7d7861ce8aa724c75192909fd8c95cbdfd9de5847b75e5d46f849c"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.4+0/Blosc.v1.21.4.i686-w64-mingw32.tar.gz"
[[Blosc]]
arch = "powerpc64le"
git-tree-sha1 = "aade64633b9490c1b15acb7bcd79b1f8c5194753"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "1ef3c6523c08c8bcae78d2d77b90c4e4923df6c3c34aafe26b891afde2fcfbe4"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.4+0/Blosc.v1.21.4.powerpc64le-linux-gnu.tar.gz"
[[Blosc]]
arch = "x86_64"
git-tree-sha1 = "561688294219302eceb4619cb69a292d0b66151a"
os = "macos"

    [[Blosc.download]]
    sha256 = "e5a80604efdc21a6b259adfc250c9e1b192c0f72d5d7501c0bfc3a8d6d399823"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.4+0/Blosc.v1.21.4.x86_64-apple-darwin.tar.gz"
[[Blosc]]
arch = "x86_64"
git-tree-sha1 = "b1d485d780339a5f9a3edac1f97a961bf359ea5f"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "282b8d96869ac7bd55771d4625fa5bb28e38a5db2063c9491aa082f91fc8be72"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.4+0/Blosc.v1.21.4.x86_64-linux-gnu.tar.gz"
[[Blosc]]
arch = "x86_64"
git-tree-sha1 = "e7014fe52aa0658975f9ec1e331a5f0734c79522"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "454688db73565ccdfa40a02c5f09c9b98fe2c7f900bd2c08c4e47077e49050cb"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.4+0/Blosc.v1.21.4.x86_64-linux-musl.tar.gz"
[[Blosc]]
arch = "x86_64"
git-tree-sha1 = "18d0f79edc040f65af684313aeea21a49f8b73f9"
os = "freebsd"

    [[Blosc.download]]
    sha256 = "6e86b39367d8fa105a452ae1b33c4572ce5814d94c8b63f95cbe547aee1e7a9e"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.4+0/Blosc.v1.21.4.x86_64-unknown-freebsd.tar.gz"
[[Blosc]]
arch = "x86_64"
git-tree-sha1 = "e48a0bacd2ce6a108c7edc024073f889d920d522"
os = "windows"

    [[Blosc.download]]
    sha256 = "9cee06752820e2b6bbd1189143173855fa8bc89691d1c29dfcbdd8a1ae9e2aa6"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.4+0/Blosc.v1.21.4.x86_64-w64-mingw32.tar.gz"
