[[Blosc]]
arch = "aarch64"
git-tree-sha1 = "80954625765f7206093bb595b4000a9665c0cb27"
os = "macos"

    [[Blosc.download]]
    sha256 = "c89ecd7b0a9e4c3d39b86ee10240aabdc08016a0823cb47e7971a9502f145432"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+0/Blosc.v1.21.6.aarch64-apple-darwin.tar.gz"
[[Blosc]]
arch = "aarch64"
git-tree-sha1 = "b2189a47f3a64044abedc7066577023fd5fcc2ea"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "9b9fdda4bd4e0aee5fdc9014578b95ef2ecdc819c39910ac837d62a2416e1784"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+0/Blosc.v1.21.6.aarch64-linux-gnu.tar.gz"
[[Blosc]]
arch = "aarch64"
git-tree-sha1 = "6c67e25d8a5ea1d69ceed27bd3b8ade2540a429a"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "b58551778a7b1c51692db3b66bc643ae3f68798a059e4011bcdf4f8b87336e4b"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+0/Blosc.v1.21.6.aarch64-linux-musl.tar.gz"
[[Blosc]]
arch = "aarch64"
git-tree-sha1 = "7796654e841d36fcdd2e4fb61e7a8882fc0ffa8c"
os = "freebsd"

    [[Blosc.download]]
    sha256 = "c8b0255ac1b0c59906094d432fb0fa06bb77d4e9087fa4f5aae4ddf36dce1a7e"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+0/Blosc.v1.21.6.aarch64-unknown-freebsd.tar.gz"
[[Blosc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c6300e58db95b0e957aa210e41e2a748935e79f2"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "c23e4ef97f15afe9ac1d0df70541d321150f621d51cd4b92bb882f6817715c37"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+0/Blosc.v1.21.6.armv6l-linux-gnueabihf.tar.gz"
[[Blosc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c58c6deb3d85a6d7bd88247549ad351df98301f8"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "9c8a404023ea387f277811fa63e4e8490f339907426b4edbf978ba28e00aadc9"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+0/Blosc.v1.21.6.armv6l-linux-musleabihf.tar.gz"
[[Blosc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ccbab8926ec2c188f9073b77e547cccf930662a2"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "3918f471d2134259fbdf8a68de5666d3df3de1856ff6550d76f65053d69d436e"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+0/Blosc.v1.21.6.armv7l-linux-gnueabihf.tar.gz"
[[Blosc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e506ff4c37ce938869b35d2f4a84b7a11bc9dda0"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "80b05941bf49c3044ca28b1108f4ee8c8d6ef01012ad36dfaa42eae9ac65ee8d"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+0/Blosc.v1.21.6.armv7l-linux-musleabihf.tar.gz"
[[Blosc]]
arch = "i686"
git-tree-sha1 = "2813beac2550554d73dc92c3670f051485e9ea0a"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "8c5e8f6902577665d7763ac1b9715b97afe41872972b2885b4dc492ee787aa2b"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+0/Blosc.v1.21.6.i686-linux-gnu.tar.gz"
[[Blosc]]
arch = "i686"
git-tree-sha1 = "b1be04d793ba323106b2b4c5b6d4b08053a74a25"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "d4b80d7b26e5a44abe4457d1f17a1141972ac906705b636936d65aeab65362b3"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+0/Blosc.v1.21.6.i686-linux-musl.tar.gz"
[[Blosc]]
arch = "i686"
git-tree-sha1 = "e07efad9de45809139e2347664903617f9d8e619"
os = "windows"

    [[Blosc.download]]
    sha256 = "2a55a923a86475c45a2efe36bf366c98af028174546547c118298de83e0eac02"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+0/Blosc.v1.21.6.i686-w64-mingw32.tar.gz"
[[Blosc]]
arch = "powerpc64le"
git-tree-sha1 = "72b413315bcf698d60904e30908b8ea43bb0e771"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "6200c4125b7b6caf22b67c9618df527aeb2929a94b407fc50108450670945803"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+0/Blosc.v1.21.6.powerpc64le-linux-gnu.tar.gz"
[[Blosc]]
arch = "x86_64"
git-tree-sha1 = "1f6113d97826297d30b168d657d49ff70ca77070"
os = "macos"

    [[Blosc.download]]
    sha256 = "397ae7514a0f991acf4c363e2ea2faec8a295b8efef0b9043cf4cbe32af95448"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+0/Blosc.v1.21.6.x86_64-apple-darwin.tar.gz"
[[Blosc]]
arch = "x86_64"
git-tree-sha1 = "7349ce11d88741e3f620e55ba0bff3d0fe77e672"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "113988876a5d78a35362a498381daa33594199d6ed2557298bde72454cf94ee0"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+0/Blosc.v1.21.6.x86_64-linux-gnu.tar.gz"
[[Blosc]]
arch = "x86_64"
git-tree-sha1 = "9c70d2d0fbde4828a4d5b87aebc48185eb9bc2af"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "65ca49dd7d4378ddda547489fd57c9a37255863d6cb7b3600fc1591b4b091e46"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+0/Blosc.v1.21.6.x86_64-linux-musl.tar.gz"
[[Blosc]]
arch = "x86_64"
git-tree-sha1 = "7c14b8413426e35d38e17c88d6f2aa913b5e4e05"
os = "freebsd"

    [[Blosc.download]]
    sha256 = "a9cad5e17762ca6620fa3af13b5ad76274036f1f617f21aa6bce10c5f67b5dcc"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+0/Blosc.v1.21.6.x86_64-unknown-freebsd.tar.gz"
[[Blosc]]
arch = "x86_64"
git-tree-sha1 = "1faca2bc7753f293a94756515af11388f239bd41"
os = "windows"

    [[Blosc.download]]
    sha256 = "2b09d21212ab7d3d37a7775141ee98f32f27e3feca117c8a981cafc37b040fe7"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.6+0/Blosc.v1.21.6.x86_64-w64-mingw32.tar.gz"
