[[Blosc]]
arch = "aarch64"
git-tree-sha1 = "0599d906760fc86a3eda5f2049e8dde064df4b99"
os = "macos"

    [[Blosc.download]]
    sha256 = "2427c81bfbe9f7e14f54035a4de8c3dfad0da29963823d8cf34bdcdd24555bfa"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.5+0/Blosc.v1.21.5.aarch64-apple-darwin.tar.gz"
[[Blosc]]
arch = "aarch64"
git-tree-sha1 = "56e01ad41329674adfaabdf4c03196d7bbb1d4a4"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "9287b3eb173124ed36c8920fd84d56a237c67a6bdb440d7e3a02843c4f7bba31"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.5+0/Blosc.v1.21.5.aarch64-linux-gnu.tar.gz"
[[Blosc]]
arch = "aarch64"
git-tree-sha1 = "705d34484516d48a9be2110b8234ae7d16bd6cae"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "5c37b703cb60d0094f2788fe5eda452ed8da9ee69f6030f55409b4da897ae7fa"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.5+0/Blosc.v1.21.5.aarch64-linux-musl.tar.gz"
[[Blosc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "439a90b056ef6c1f86826b42f64ed9a13ac5c1b5"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "c66c5c7aaed0763a5a89c41561f806b06456186544280e59087ab5df87294e8f"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.5+0/Blosc.v1.21.5.armv6l-linux-gnueabihf.tar.gz"
[[Blosc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4eede7fb822f4c517b85229a54dbcd44619426ba"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "1b5a524310ebeaecca97f267d358784852ceda389d645f6f29abdbf35ee1bf21"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.5+0/Blosc.v1.21.5.armv6l-linux-musleabihf.tar.gz"
[[Blosc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d2dfb39046165e735d0f58b7d090738086739e93"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "00baee670b9cdb1c4aa8c6f7469089b26afb409296d708faae19cdd829667838"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.5+0/Blosc.v1.21.5.armv7l-linux-gnueabihf.tar.gz"
[[Blosc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "92b3a443a0536fc7db41ce1ecab78cdd565eaa29"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "d711098e2bf1ebbf82f6b7a6db43921c83a596b701c02696044211b414cd0b10"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.5+0/Blosc.v1.21.5.armv7l-linux-musleabihf.tar.gz"
[[Blosc]]
arch = "i686"
git-tree-sha1 = "b56538d4f41414821266e172146f3d548ddd26f3"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "e17b17344f174f040ef146c03cd65b1bbba91bc7213c815ab26b101b1cf5d3f0"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.5+0/Blosc.v1.21.5.i686-linux-gnu.tar.gz"
[[Blosc]]
arch = "i686"
git-tree-sha1 = "94475f98f60ffea14240f7168e53d97938ce3d9b"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "4359e82feb84286647a7c5477a66d767b62aada87dd1073685f3e3b58bde3faa"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.5+0/Blosc.v1.21.5.i686-linux-musl.tar.gz"
[[Blosc]]
arch = "i686"
git-tree-sha1 = "c35ae666db72f970c47c97018bf2e32a950fc084"
os = "windows"

    [[Blosc.download]]
    sha256 = "e51fd8cab5ff470737cde1926cc1aff7fa7983afdcd41dc521e1a19cfa0e0116"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.5+0/Blosc.v1.21.5.i686-w64-mingw32.tar.gz"
[[Blosc]]
arch = "powerpc64le"
git-tree-sha1 = "65a9d769b63e3e5e48237d9cea26826982107a43"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "1ed52adcabb0e588797286816eefa171b5d7efe7a6486ed44a45c6ead2640fd3"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.5+0/Blosc.v1.21.5.powerpc64le-linux-gnu.tar.gz"
[[Blosc]]
arch = "x86_64"
git-tree-sha1 = "afa5d0e0b77b70a267a9b6e8732268936d85fbb7"
os = "macos"

    [[Blosc.download]]
    sha256 = "c8adc62e4f324deb970cf1247fd4c60b856cb8561219557a641a373f74d9c893"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.5+0/Blosc.v1.21.5.x86_64-apple-darwin.tar.gz"
[[Blosc]]
arch = "x86_64"
git-tree-sha1 = "7969c83077619d040d72f0549771cd9506c5c1bd"
libc = "glibc"
os = "linux"

    [[Blosc.download]]
    sha256 = "bf26863620b326b43af188b93756b23ad3dcac0518f48fd1411a26a934d9701c"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.5+0/Blosc.v1.21.5.x86_64-linux-gnu.tar.gz"
[[Blosc]]
arch = "x86_64"
git-tree-sha1 = "79acaff1c60a07517ed7ddfe1dbc8f8648e0b3d7"
libc = "musl"
os = "linux"

    [[Blosc.download]]
    sha256 = "51b8be07b31aca4bb8ecd412c720da23f883cf6a5edc8a2e946874c976d800b0"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.5+0/Blosc.v1.21.5.x86_64-linux-musl.tar.gz"
[[Blosc]]
arch = "x86_64"
git-tree-sha1 = "129b074ecc67272d1253fa7bdee5cd68cd74fcce"
os = "freebsd"

    [[Blosc.download]]
    sha256 = "8a797d8f0698f0cad4ba4249bd82a6d8c46fba2292d65d16eaf7a0c7240c6be2"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.5+0/Blosc.v1.21.5.x86_64-unknown-freebsd.tar.gz"
[[Blosc]]
arch = "x86_64"
git-tree-sha1 = "0c22dcb4dc0caba86c5166d4af5f5c02cd6abeb6"
os = "windows"

    [[Blosc.download]]
    sha256 = "a9e0d2139c26a842c49b98b3cfc57d7015dc5e62470d7cd7a5e7a960fa734c00"
    url = "https://github.com/JuliaBinaryWrappers/Blosc_jll.jl/releases/download/Blosc-v1.21.5+0/Blosc.v1.21.5.x86_64-w64-mingw32.tar.gz"
